name: lista_de_filmes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  google_maps: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff" # cor de fundo da splash
  image: assets/logo.png # sua logo (coloque em assets)

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
